"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import cloudinary
import cloudinary.uploader
import cloudinary.api

from pathlib import Path

import os
import dj_database_url # <--- Add this import
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%teu+=y_bs-@_61w^f7nkau#+sudi^5nw5*gkhq(+fw^!uks^3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Force update for Render allowed hosts

CSRF_TRUSTED_ORIGINS = [
    'https://tracker-r7wq.onrender.com',  # <--- Note the HTTPS://
    'http://127.0.0.1:8000',
]

# Application definition

INSTALLED_APPS = [
    'tracker',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEBUG = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'tracker.User'


cloudinary.config( 
  cloud_name = "dq81tcsis", 
  api_key = "399821466415555", 
  api_secret = "l-1s9A2_FKra39expkv3V2hR-Go" 
)

# Cloudinary Setup (We will add real keys later)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dq81tcsis', 
    'API_KEY': '399821466415555', 
    'API_SECRET': 'l-1s9A2_FKra39expkv3V2hR-Go',
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Redirect to home/dashboard after successful login
LOGIN_REDIRECT_URL = 'dashboard'
# Redirect to login page after logout
LOGOUT_REDIRECT_URL = 'login'

# Static files configuration
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# ==========================================
# SECURITY & SESSION HARDENING
# ==========================================

# 1. AUTO-LOGOUT: Users are kicked out after 30 minutes of inactivity
SESSION_COOKIE_AGE = 30 * 60  # 30 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Reset the timer if they are active

# 2. DEVICE ISOLATION: Closing the browser = Logging out
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 3. COOKIE SECURITY: Prevent hackers (and sync features) from stealing cookies
SESSION_COOKIE_SECURE = True   # Only send cookies over HTTPS
SESSION_COOKIE_HTTPONLY = True # Prevent JavaScript from reading cookies
CSRF_COOKIE_SECURE = True      # Encrypt the CSRF token
CSRF_COOKIE_HTTPONLY = True

# 4. PREVENT CACHING: Tell the phone "Do not save this page"
# (This ensures the dashboard always reloads fresh from the server)
CACHE_MIDDLEWARE_SECONDS = 0

# 5. STRICT BROWSER RULES
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'       # Prevents your site from being put in an iframe