# Generated by Django 5.0.1 on 2025-12-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_client_alter_itemfielddefinition_excel_column_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.CharField(default='Client', max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='tracker.pole')),
            ],
        ),
    ]
